In [1]:
import numpy as np

actions = np.zeros(6)
print(actions)
actions = np.reshape(actions,(3,2))
print(actions)


[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
actions = np.reshape(actions,(1,6))[0]
print(actions)

[0. 0. 0. 0. 0. 0.]


In [3]:
print(np.zeros(2))

[0. 0.]


In [4]:
a = np.array([1,2,3,4,5])
print(a)
a = np.flip(a,0)
print(a)

[1 2 3 4 5]
[5 4 3 2 1]


In [6]:
a = np.random.randn(2, 2)
print(a)
a = np.flip(a,0)
print(a)

[[ 1.25941186 -2.0455863 ]
 [-1.46014014  0.66471184]]
[[-1.46014014  0.66471184]
 [ 1.25941186 -2.0455863 ]]
