In [1]:
import numpy as np

actions = np.zeros(6)
print(actions)
actions = np.reshape(actions,(3,2))
print(actions)


[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
actions = np.reshape(actions,(1,6))[0]
print(actions)

[0. 0. 0. 0. 0. 0.]


In [3]:
print(np.zeros(2))

[0. 0.]


In [4]:
a = np.array([1,2,3,4,5])
print(a)
a = np.flip(a,0)
print(a)

[1 2 3 4 5]
[5 4 3 2 1]


In [5]:
a = np.random.randn(2, 2)
print(a)
a = np.flip(a,0)
print(a)

[[2.55564504 1.04173177]
 [1.11345605 0.72528167]]
[[1.11345605 0.72528167]
 [2.55564504 1.04173177]]


In [11]:
import time
for i in range(10):
    time.sleep(1)
    print("\033[F" + str(i) + "\n" + "\033[F"+ str(i+1) + "\n" + "\033[F"+ str(i+2), end = "" , flush = True)
    #print('\rEpisode {:d}\tmax score: {:.2f}\taverage maximum score over the last 10 episodes: {:.2f}'.format(i, i+1, i, end=""))

0
1
21
2
32
3
43
4
54
5
65
6
76
7
87
8
98
9
109
10
11